name: Python package

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: false
        create-args: python=${{ matrix.python-version }}
        post-cleanup: 'all'
    - name: Print Python version
      shell: bash -el {0}
      run: |
        python --version
    - name: Run pytest
      shell: bash -el {0}
      run: |
        pytest
