name: tests

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: false
        create-args: python=${{ matrix.python-version }}
        post-cleanup: 'all'
    - name: Install xcengine
      shell: bash -el {0}
      run: |
        python --version
        pip install --no-deps --editable .
    - name: Run pytest
      shell: bash -el {0}
      run: |
        pytest --cov=xcengine --cov-branch --cov-report=xml
    - uses: codecov/codecov-action@v5
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
